presubmits:
  ImitationImmortal/test-prow:
    - name: post-test-ImitationImmortal-deploy-prow
      decorate: true
      branches:
        - ^main$
      max_concurrency: 1
      spec:
        containers:
          - image: alpine:3.19
            command:
              - echo
              - "success"
