presubmits:
  kubesphere/kubesphere:
  - name: pull-kubesphere-unit-test
    labels:
      preset-go-build-cache: "true"
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: kubesphere.io/kubesphere
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: kubesphere/build-tools:master-latest
        name: ""
        resources:
          limits:
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 2Gi
        # securityContext:
        #   privileged: true
  - name: pull-kubesphere-verify
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: kubesphere.io/kubesphere
    spec:
      containers:
      - command:
        - entrypoint
        - bash
        - -e
        - -c
        - "make verify-all"
        image: kubesphere/build-tools:master-latest
        name: ""
        resources:
          limits:
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 2Gi
