---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .namespace }}"

---
apiVersion: v1
kind: Secret
metadata:
  namespace: "{{ .namespace }}"
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "{{ .storage.qingcloud.region }}",
      "access_key": "{{ .storage.qingcloud.access_key }}",
      "endpoint": "{{ .storage.qingcloud.endpoint }}",
      "insecure": {{ .storage.insecure }},
      "s3_force_path_style": {{ .storage.s3_force_path_style }},
      "secret_key": "{{ .storage.qingcloud.secret_key }}"
    }
