apiVersion: v1
kind: Secret
metadata:
  namespace: "{{ namespace }}"
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "{{ storage.qingcloud.region }}",
      "access_key": "{{ storage.qingcloud.access_key }}",
      "endpoint": "{{ storage.qingcloud.endpoint }}",
      "insecure": true,
      "s3_force_path_style": true,
      "secret_key": "{{ storage.qingcloud.secret_key }}"
    }
