---
- name: deploy minio storage
  tags: ["minio"]
  block:
    - name: sync minio to remote
      template:
        src: storage/minio.yaml
        dest: prow-storage-minio.yaml
    - name: apply minio
      command: |
        kubectl apply -f prow-storage-minio.yaml

- name: deploy qingcloud storage
  tags: ["qingstor"]
  block:
    - name: check qingcloud args
      block:
        - name: check if qingcloud region is set
          assert:
            that: .storage.qingcloud.region | ne ""
            msg: "qingcloud region should set"
        - name: check if qingcloud endpoint is set
          assert:
            that: .storage.qingcloud.endpoint | ne ""
            msg: "qingcloud endpoint should set"
        - name: check if qingcloud access_key is set
          assert:
            that: .storage.qingcloud.access_key | ne ""
            msg: "qingcloud access_key should set"
        - name: check if qingcloud secret_key is set
          assert:
            that: .storage.qingcloud.secret_key | ne ""
            msg: "qingcloud secret_key should set"
    - name: sync qingcloud to remote
      template:
        src: storage/qingcloud.yaml
        dest: prow-storage-qingcloud.yaml
    - name: apply qingcloud
      command: |
        kubectl apply -f prow-storage-qingcloud.yaml
