---
- name: deploy minio storage
  tags: ["minio"]
  block:
    - name: sync minio to remote
      template:
        src: storage/minio.yaml
        dest: prow-storage-minio.yaml
    - name: apply minio
      command: |
        kubectl apply -f prow-storage-minio.yaml

- name: deploy qingcloud storage
  tags: ["qingcloud"]
  block:
    - name: check qingcloud args
      block:
        - name: check if qingcloud access_key is set
          assert: storage.qingcloud.access_key != ""
          msg: "qingcloud access_key should set"
        - name: check if qingcloud secret_key is set
          assert: storage.qingcloud.secret_key != ""
          msg: "qingcloud secret_key should set"
    - name: sync qingcloud to remote
      template:
        src: storage/qingcloud.yaml
        dest: prow-storage-qingcloud.yaml
    - name: apply qingcloud
      command: |
        kubectl apply -f prow-storage-qingcloud.yaml
