postsubmits:
  kubesphere/console:
  - name: pull-console-build-image
    labels:
      preset-docker-sock: "true"
      preset-docker-credentials: "true"
    always_run: true
    branches:
    - ^master$
    - release-*
    decorate: true
    spec:
      containers:
      - command:
        - "/bin/sh"
        - "-c"
        - "make image && make image-push"
        image: kubesphere/build-tools:master-latest
        name: ""
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          securityContext:
            privileged: true

periodics:
- interval: 24h
  decorate: true
  branches: master
  extra_refs:
  - org: kubesphere
    repo: console
    base_ref: master
  name: kubesphere-console-periodic-build-image
  labels:
    preset-docker-sock: "true"
    preset-docker-credentials: "true"
  spec:
    containers:
    - image: kubesphere/build-tools:master-latest
      command:
      - "/bin/sh"
      - "-c"
      - export TAG=nightly-$(date "+%Y%m%d") && make image && make image-push
      # docker-in-docker needs privileged mode
      securityContext:
        priviledged: true
      resources:
        requests:
          cpu: 1
          memory: "2Gi"
  annotations:
    description: "Periodic builds and pushs"
