presubmits:
  kubesphere/console:
  - name: pull-console-unit-test
    always_run: false
    decorate: true
    spec:
      containers:
      - command:
        - entrypoint
        - yarn && yarn test
        image: node:12.18
        name: ""
        resources:
          limits:
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 2Gi
  - name: pull-console-build
    always_run: false
    decorate: true
    spec:
      containers:
      - command:
        - entrypoint
        - yarn && yarn build
        image: node:12.18
        name: ""
        resources:
          limits:
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 2Gi
